dayds/aljalddakggalco

.gitignore, .idea/.gitignore, .idea/aljalddakggalco.iml, .idea/inspectionProfiles/Project_Default.xml, .idea/inspectionProfiles/profiles_settings.xml, .idea/misc.xml, .idea/modules.xml, .idea/vcs.xml, N4YE/W1/Programmers_인덱스바꾸기.py, N4YE/W1/baekjoon_23322_초콜릿뺏어먹기.py, N4YE/W1/baekjoon_30019_강의실예약시스템.py, N4YE/W1/programmers_약수구하기.py, N4YE/W1/programmers_한번만등장한문자.py, N4YE/W2/baekjoon_1417_국회의원선거.py, N4YE/W2/baekjoon_7785_회사에있는사람.py, N4YE/W2/programmers_가장큰수찾기.py, N4YE/W2/programmers_문자열계산하기.py, N4YE/W2/programmers_편지.py
---
연두는 `N개의 통`에 초콜릿을 담아 오름차순으로 배열해둔다. 효원이가 연두의 초콜릿을 몰래 뺏어먹을 때, `K`<i인 i를 골라 i-K번째 통에 있는 초콜릿의 개수와 똑같아질 때까지 i번째 통에서 초콜릿을 뺏어먹고 이후 통을 다시 오름차순으로 재정렬한다고 한다. 연두가 눈치채지 못하는 선에서 최대한 많이, 그리고 최대한 빨리 초콜릿을 먹어 치우고 싶다면 과연 몇 개나 먹을 수 있을까?
<aside>
✏️
N : 초콜릿 통 개수
K  :  *(i-K)라는걸 이해 못함. 최솟값 기준으로 했다!*
chocolate : 초콜릿 통 배열
count : 먹을 수 있는 초콜릿의 최대 개수
day : 초콜릿을 먹기위해 필요한 최소 날짜
</aside>
```python
N, K = map(int, input().split())
chocolate = list(map(int, input().split()))
count = 0  # 최대 초콜릿
day = 0    # 최소 날짜
min_choco = min(chocolate)  # 초콜릿 개수 기준값
for i in range(N):
if chocolate[i] > min_choco:  # 초콜릿이 기준 값보다 많을 경우
count += (chocolate[i] - min_choco)  # 초콜릿 냠냠
chocolate[i] = min_choco  # 냠냠 -> 최소 개수
day += 1  # 하루 종료!
print(count, day)
```
문제에서 K값이라는 것을 잘 이해하지 못해 예시 답변 출력에서 최솟값이 …
=> [DSCT-2] GitHub PR 1주차

Moon-ye-rin/2주차/[백준]#1417 국회의원 선거.py, Moon-ye-rin/2주차/[백준]#7785 회사에 있는 사람.py, Moon-ye-rin/2주차/[프로그래머스] 7의 개수.py, Moon-ye-rin/2주차/[프로그래머스] 머쓱이보다 키 큰 사람.py, Moon-ye-rin/2주차/[프로그래머스] 잘라서 배열로 저장하기.py, Moon-ye-rin/2주차/[프로그래머스] 중복된 숫자 개수.py
**📍작성한 플로우**
[변수 정의]
- n : 출입 기록의 수
- person: 사람을 저장하기 위한 set
- name: 로그에 기록된 사람의 이름
- action: 출근, 혹은 퇴근
1. 첫번째 줄에서 로그 출입 기록 수 n을 입력받는다.
2. 회사에 있는 사람을 저장하기 위해 빈 집합을 생성.
3. n번 만큼 for문을 돈다.
3-1. 만약 출근을 했을 경우 집합에 이름을 추가한다.
3-2. 퇴근을 했을 경우 집합에 이름을 삭제한다.
4. 이름을 사전 역순으로 정렬하고 출력한다.
**📍작성한 코드**
```python
import sys
n = int(sys.stdin.readline().strip())  # 첫 번째 줄에서 n 입력받기
person = set()  # 회사에 있는 사람을 저장하기 위한 집합 사용
name, action = sys.stdin.readline().strip().split()  # 이름과 행동 입력받기
if action == 'enter':  # 'enter'일 경우
person.add(name)  # 집합에 사람 추가
else:  # 'leave'일 경우
person.discard(name)  #집합에 사람 삭제
for name in sorted(person, reverse=True):
print(name)
```
**📍소감**
- 문제의 구성 자체는 어렵지 않았으나, 자꾸 시간 초과가 발생하여 이를 해결하기 위해 구글링을 하였고, list 대신 set자료형을 사용하였더니 정답처리가 되었습니다. 찾아보니 list와 set의 시간 복잡도 …
=> [DSCT-9] GitHub PR 2주차

BOJ_1417.py, BOJ_7785.py, PRG_week2_1.py, PRG_week2_2.py, PRG_week2_3.py, PRG_week2_4.py
1. 출입기록 수(count) input
2. for문 안에서 진행(count만큼 반복)
3. 사람(name)과 출입기록(el) input
4. el이 enter일 경우 name을 list(company)에 입력
5. el이 leave일 경우 name을 list(company)에서 제거
6. 사전 순의 역순으로 출력
```
import sys
count = int(sys.stdin.readline())
company = []
for i in range(count):
name,el = map(str, sys.stdin.readline().split())
if el == 'enter':
company.append(name)
elif el == 'leave':
company.remove(name)
for x in reversed(sorted(company)):
print(x)
```
- 시간 부족으로 sys 사용
- sys를 사용해도 시간 부족
- for문 안에서 input을 받아 시간 초과가 발생한 것 같음
저번주에 진행한 코테에서도 시간 부족으로 발생한 문제를 이번에는 sys를 사용하여 보완했지만, 이번에는 sys를 사용해도 시간이 부족하였다. 이 문제는 코드가 복잡하여 시간 복잡도가 늘어난 것으로 발행한 문제 같았다. 좀 더 간결한 코드를 작성하는 연습을 더 해야할 것 같다.
1. 후보의 수(N) input
2. for문 안에서 진행(N만큼 반복) 
3. list에 득표수 input
??
```
import sys
n = int(sys.stdin.readline()) # 후보 수
dasom = …
```
=> [DSCT-11] GitHub PR 2주차

sohds/w3/문제풀이/[BOJ] 날짜 계산.py, sohds/w3/문제풀이/[BOJ] 소수 부르기 게임.py, sohds/w3/문제풀이/[PGS] 옹알이 (2).py, sohds/w3/발제문제/[BOJ] 단지번호붙이기.py, sohds/w3/발제문제/[BOJ] 바이러스.py
<h1>3주차 목표
: DFS/BFS 알고리즘 문제 해결</h1>
---
신종 바이러스인 웜 바이러스는 네트워크를 통해 전파된다. 한 컴퓨터가 웜 바이러스에 걸리면 그 컴퓨터와 네트워크 상에서 연결되어 있는 모든 컴퓨터는 웜 바이러스에 걸리게 된다.
예를 들어 7대의 컴퓨터가 <그림 1>과 같이 네트워크 상에서 연결되어 있다고 하자. 1번 컴퓨터가 웜 바이러스에 걸리면 웜 바이러스는 2번과 5번 컴퓨터를 거쳐 3번과 6번 컴퓨터까지 전파되어 2, 3, 5, 6 네 대의 컴퓨터는 웜 바이러스에 걸리게 된다. 하지만 4번과 7번 컴퓨터는 1번 컴퓨터와 네트워크상에서 연결되어 있지 않기 때문에 영향을 받지 않는다.
어느 날 1번 컴퓨터가 웜 바이러스에 걸렸다. 컴퓨터의 수와 네트워크 상에서 서로 연결되어 있는 정보가 주어질 때, 1번 컴퓨터를 통해 웜 바이러스에 걸리게 되는 컴퓨터의 수를 출력하는 프로그램을 작성하시오.
```python
import sys
n = int(input())
m = int(input())
graph = [[] for _ in range(n+1)]
visited = [False] * (n+1)
for _ in range(m):
a, b = map(int, input().split())
graph[a].append(b)
graph[b].append(a)  # 쌍방 연결
def dfs(v):
visited[v] = True
for i in graph[v]:
if not …
```
=> [DSCT-15] W3 우선탐색 알고리즘 문제 해결

Moon-ye-rin/3주차/[백준]#2606 바이러스.py, Moon-ye-rin/3주차/[백준]#2667 단지번호붙이기.py, Moon-ye-rin/3주차/[프로그래머스] 다항식 더하기.py, Moon-ye-rin/3주차/[프로그래머스] 직사각형 넓이 구하기.py, Moon-ye-rin/3주차/[프로그래머스] 최댓값 만들기 (2).py, Moon-ye-rin/3주차/[프로그래머스] 캐릭터의 좌표.py
**📍작성한 플로우**
1. 컴퓨터 개수를 n으로 입력받고, 3번째 줄 이후인 연결쌍을 tuple로 입력받는다.
2. 노드 연결을 저장하기 위해 n+1 크기로 리스트를 생성
3. 인접 리스트(무방향 그래프)를 구현
4. BFS 탐색
5. 방문한 노드 개수에서 1번 노드를 제외한 개수를 출력
**📍작성한 코드**
```python
import sys
from collections import deque
input = sys.stdin.read
data = input().splitlines()
n = int(data[0])   
arr = [tuple(map(int, line.split())) for line in data[2:]]
agi_list = [[] for _ in range(n + 1)]
for a, b in arr:
agi_list[a].append(b)
agi_list[b].append(a)
def bfs(start):
visited = set()
queue = deque([start])
while queue:
node = queue.popleft()
if node not in visited:
visited.add(node)
queue.extend(agi_list[node])  # 현재 노드와 연결된 노드 추가
return len(visited) - 1  # 1번 노드 제외 후 반환
print(bfs(1))
```
**📍소감**
- 이론으로만 배운 그래프를 코드로 직접 구현하는 것은 처음이라 생각보다 많은 시간이 걸렸습니다. 또한 BFS(너비 우선 탐색) 함수는 직접 구현하기에는 한계가 있어 …
=> [DSCT-14] GitHub PR 3주차

N4YE/W3/baekjoon_2606_바이러스.py, N4YE/W3/baekjoon_2667_단지번호붙이기.py, N4YE/W3/programmers_n의배수고르기.py, N4YE/W3/programmers_배열의유사도.py, N4YE/W3/programmers_숫자찾기.py
3주차 PR (@N4YE) 
---
신종 바이러스인 웜 바이러스는 네트워크를 통해 전파된다. 한 컴퓨터가 웜 바이러스에 걸리면 그 컴퓨터와 네트워크 상에서 연결되어 있는 모든 컴퓨터는 웜 바이러스에 걸리게 된다.
예를 들어 7대의 컴퓨터가 <그림 1>과 같이 네트워크 상에서 연결되어 있다고 하자. 1번 컴퓨터가 웜 바이러스에 걸리면 웜 바이러스는 2번과 5번 컴퓨터를 거쳐 3번과 6번 컴퓨터까지 전파되어 2, 3, 5, 6 네 대의 컴퓨터는 웜 바이러스에 걸리게 된다. 하지만 4번과 7번 컴퓨터는 1번 컴퓨터와 네트워크상에서 연결되어 있지 않기 때문에 영향을 받지 않는다.
어느 날 1번 컴퓨터가 웜 바이러스에 걸렸다. 컴퓨터의 수와 네트워크 상에서 서로 연결되어 있는 정보가 주어질 때, 1번 컴퓨터를 통해 웜 바이러스에 걸리게 되는 컴퓨터의 수를 출력하는 프로그램을 작성하시오.
```python
import sys
N = int(input())   # 컴퓨터의 수
M = int(input())   # 네트워크 상 연결된 컴퓨터 쌍의 수
graph = [[] for _ in range(N+1)]        # 그래프 생성
for i in range(M):
a, b = map(int, input().split())
graph[a].append(b)
graph[b].append(a)
visited = [0] * (N+1)               # 방문여부 표시
count = …
```
=> [DSCT-13] GitHub PR 3주차

sohds/w4/문제풀이/[PGS] 금과 은 운반하기.py, sohds/w4/문제풀이/[PGS] 달리기 경주.py, sohds/w4/문제풀이/[PGS] 문자열 나누기.py, sohds/w4/발제문제/[BOJ] 나이순 정렬.py, sohds/w4/발제문제/[BOJ] 수 정렬하기 2.py
<h1>4주차 목표
: 정렬 알고리즘 문제 해결</h1>
---
N개의 수가 주어졌을 때, 이를 오름차순으로 정렬하는 프로그램을 작성하시오.
```python
import sys
n = int(sys.stdin.readline())
arr = []
for _ in range(n):
arr.append(int(sys.stdin.readline()))
for i in sorted(arr):
print(i)
```
```python
def merge_sort(arr):
if len(arr) <= 1:
return arr
mid = len(arr) // 2
left = merge_sort(arr[:mid])
right = merge_sort(arr[mid:])
return merge(left, right)
def merge(left, right):
result = []
i, j = 0, 0
while i < len(left) and j < len(right):
if left[i] < right[j]:
result.append(left[i])
i += 1
else:
result.append(right[j])
j += 1
result.extend(left[i:])
result.extend(right[j:])
return result
sorted_arr = merge_sort(arr)
for i in sorted_arr:
print(i)
```
뒤이어 문제도 그런 방식으로 풀었지만, 파이썬에는 내장함수로 정렬함수가 있기 때문에 정렬함수로도 풀고, 새롭게 도전해보기 …
=> [DSCT-21] W4 정렬 알고리즘 문제 해결

Moon-ye-rin/4주차/[백준]#10814 나이순 정렬.py, Moon-ye-rin/4주차/[백준]#2751 수 정렬하기 2.py, Moon-ye-rin/4주차/[프로그래머스] 삼각형의 완성조건 (2).py, Moon-ye-rin/4주차/[프로그래머스] 숨어있는 숫자의 덧셈 (2).py, Moon-ye-rin/4주차/[프로그래머스] 안전지대.py, Moon-ye-rin/4주차/[프로그래머스] 외계어 사전.py
**📍작성한 플로우**
1. 데이터 입력 (n: 리스트 길이, arr: 1차원 리스트)
2. 파이썬 함수 sort 정렬
3. 줄바꿈으로 결과 출력
**📍작성한 코드**
```python
import sys
input = sys.stdin.read
data = input().splitlines()
n = int(data[0])
arr = list(map(int, data[1:]))
arr.sort()
print(*arr, sep='\n')
'''
def quick_sort(array, start, end):
if start >= end:   # 원소가 1개 이하면 종료
return
pivot = start   # 첫번째 원소를 피벗으로 설정
left = start + 1
right = end
while left <= right:
while left <= end and array[left] <= array[pivot]:
left += 1   # 왼쪽으로부터 피벗보다 큰 데이터를 찾을 때까지 이동
while right > start and array[right] >= array[pivot]:
right -= 1   # 끝에서부터 오른쪽으로 피벗보다 작은 데이터를 찾을 때까지 이동
if left > right:   # 왼쪽과 오른쪽이 엇갈린다면
array[right], array[pivot] = array[pivot], array[right]   # 피벗을 작은 데이터와 교체
else:
array[left], array[right] = array[right], array[left] …
```
=> [DSCT-20] GitHub PR 4주차

NaK_week4/BOJ_10814.py, NaK_week4/BOJ_2751.py, NaK_week4/PRG_배열원소의길이.py, NaK_week4/PRG_삼각형의완벽조건1.py, NaK_week4/PRG_중복된문자제거.py, NaK_week4/PRG_컨트롤제트.py
```
import sys
n = int(sys.stdin.readline()) # 수의 개수
count = []
count.append(int(sys.stdin.readline()))
count.sort()
print(count[i])
```
문제 이해가 쉽고 플로우를 작성하지 않아도 간단하게 코드 작성이 가능했습니다. 다만 이보다 코드를 더 간소화 할 수 있을 것 같았고, 정렬 알고리즘을 사용하지 않고 파이썬 내장 함수를 사용하여 다른 방법으로 코드 작성하는 연습을 더 해봐야 할 것 같습니다.
1. 입력 받기
1-1. 나이와 이름은 for문 안에서 입력 받기
2. 나이, 이름을 리스트 저장하여 정렬
```
import sys
n = int(sys.stdin.readline().strip())
members = []
age, name = sys.stdin.readline().split()
members.append((int(age), i, name))  # 나이, 가입 순서, 이름 저장
members.sort(key=lambda x: (x[0], x[1]))
for age, _, name in members:
print(age, name)
```
처음에는 리스트를 정렬하는 방법이 아닌 딕셔너리를 활용하여 정렬하려고 하였습니다. 다만, 딕셔너리를 사용하지 key 중복이 불가능하여 찾아보니 리스트 안에 리스트 형태로 저장이 가능하다는 것을 알았습니다. 학교 수업시간에 배웠던거 같은데 이렇게 활용을 하려고 하니 …
=> [DSCT-22] GitHub PR 4주차

sohds/w5/문제풀이/[PGS] [PCCE 기출문제] 10번-데이터분석.py, sohds/w5/문제풀이/[PGS] 기사단원의 무기.py, sohds/w5/문제풀이/[PGS] 둘만의 암호.py, sohds/w5/발제문제/[BOJ] 네잎 클로버를 찾아서.py, sohds/w5/발제문제/[BOJ] 주식.py
<h1>5주차 목표
: 이진탐색 알고리즘 문제 해결</h1>
---
어느 날 당신은 출근길에, 지하철역 쓰레기통에서 놀라운 문서를 얻게 되었다. 이 문서는 미래의 어떤 회사의 주식 가격의 변동이 담겨 있었다. 설마 하는 마음으로 이 회사의 주식 가격의 변동을 본 결과, 문서에 담긴 내용이 사실이라는 것을 알게 되었다. 아마도 미래에서 타임머신을 타고 온 후손이 선조를 돕기 위해서 보낸 것이 아닐까 하는 마음이 들었다.
앞으로 N 일간 주식 가격이 N 개의 숫자로 주어져 있다. 당신은 지금까지 주식이라는 것을 거래해본 적이 없기 대문에, 증권회사에 가서 거래를 시작하기로 했다. 미래를 알면서 주식을 거래한다면 다른 사람들이 의심할지도 모른다는 생각이 들어서, 총 K 번 주식을 사기로 했다. 하루에는 주식을 한 번만 살수 있기 때문에, 주식을 사는 날은 총 K 일이다.
의심을 더 줄이기 위해서, 주식을 살 때마다 맨 처음을 제외하고는 바로 직전에 주식을 샀을 때보다 가격이 올라갔을 때만 사기로 했다. 예를 들어, 10일간 주가의 변동이 다음 표와 같다고 하자.
|날짜|1|2|3|4|5|6|7|8|9|10|
|---|---|---|---|---|---|---|---|---|---|---|
|주가|100|50|70|90|75|87|105|78|110|60|
K=3이라면, 2일, 3일, 4일에 주식을 사면 그날의 주가는 50, 70, 90이기 대문에 주어진 조건을 만족한다. 만약 K=6이라면, 2일, 3일, 5일, 6일, 7일, 9일에 주식을 사면 주가가 …
=> [DSCT-27] W5 이진 탐색 알고리즘 문제 해결

sua/w5/baekjoon_w5_1.py, sua/w5/baekjoon_w5_2.py, sua/w5/programmers_w5_1.py, sua/w5/programmers_w5_2.py, sua/w5/programmers_w5_3.py, sua/w5/programmers_w5_4.py
🔵 플로우
1. 이진 탐색 함수 정의
2. lis에서 target이 들어갈 자리 찾기
3. 값이 크면 오른쪽, 작으면 왼쪽을 탐색하여 위치 반환
4. 테스트 케이스 개수 입력
5. 각 테스트 케이스 실행
6. lis 배열 초기화
7. 현재 숫자가 lis의 마지막 값보다 크면 그대로 추가
8. 작거나 같으면 이진 탐색을 사용해 적절한 위치에 값 대체
9. len(lis) >= k면 1 출력, 그렇지 않으면 0 출력
🔵 코드
```python
def binary_search(left, right, target):
while left <= right:
mid = (left + right) // 2
if lis[mid] < target:
left = mid + 1
else:
right = mid - 1
return left
test_case = int(input())
for tc in range(1, test_case+1):
N, K = map(int, input().split())
numbers = list(map(int, input().split()))
lis = [numbers[0]]
for i in range(1, N):
if lis[-1] < numbers[i]:
lis.append(numbers[i])
else:
j = binary_search(0, len(lis)-1, numbers[i])
lis[j] = numbers[i]
print('Case #{}'.format(tc))
if len(lis) >= K:
print(1)
else:
print(0)
```
🔵 피드백
문제는 이해를 하였지만 코드를 …
=> [DSCT-24] GitHub PR 5주차

NaK/NaK_week5/BOJ_12014.py, NaK/NaK_week5/BOJ_3089.py, NaK/NaK_week5/PRG_369게임.py, NaK/NaK_week5/PRG_가까운수.py, NaK/NaK_week5/PRG_대문자와 소문자.py, NaK/NaK_week5/PRG_암호해독.py
1. T(케이스 개수) 입력받기
2. T만큼 반복
2-1. n,k 입력받기
2-2. n만큼 반복하여 주가 입력받기
3. 입력받은 주가 안에서 거래 횟수(k)가 가능한지?
3-1. 두번째[1]부터 시작
3-2. 두번째 수보다 뒤에 수가 클 때 count +1
3-3. 총 count가 k보다 크거나 같다면 1 출력, 아니면 0 출력
```
import sys
T = int(sys.stdin.readline()) # 케이스 개수
answer =[]
for i in range(T):
n,k = map(int, sys.stdin.readline().split())
stock = list(map(int, sys.stdin.readline().split()))
count = 0
for i in range(1,n):
if stock[i] >= stock[i-1]:
count += 1
if count < k:
answer.append(0)
else:
answer.append(1)
for i in range(T):
print(f'Case #{i+1}')
print(answer[i])
```
지금까지 풀었던 코테들을 바탕으로 열심히 풀었던 것 같다. 확실히 이전에는 플로우를 짜지 않고 바로 코딩을 작성하였는데, 플로우를 짜면서부터 풀이의 방향성이 잡히니 술술 풀렸던 것 같다. 플로우를 잘 짤 수 있도록 계속 연습해봐야겠다.
(0,0)에서 출발
U -> 도착지점 y값 - 현재지점 y값: 양수, 절대값이 가장 작은
D -> 도착지점 y값 - 현재지점 y값: 음수, 절대값이 가장 작은
R -> 도착지점 x값 - 현재지점 x값: …
=> [DSCT-28] GitHub PR 5주차

N4YE/W5/baekjoon_12014번_주식.py, N4YE/W5/baekjoon_3089_네잎클로버를찾아서.py, N4YE/W5/prograamers_문자열안에문자열.py, N4YE/W5/programmers_문자열정렬하기(2).py, N4YE/W5/programmers_자릿수더하기.py
5주차 PR (@N4YE) 
---
어느 날 당신은 출근길에, 지하철역 쓰레기통에서 놀라운 문서를 얻게 되었다. 이 문서는 미래의 어떤 회사의 주식 가격의 변동이 담겨 있었다. 설마 하는 마음으로 이 회사의 주식 가격의 변동을 본 결과, 문서에 담긴 내용이 사실이라는 것을 알게 되었다. 아마도 미래에서 타임머신을 타고 온 후손이 선조를 돕기 위해서 보낸 것이 아닐까 하는 마음이 들었다.
앞으로 N 일간 주식 가격이 N 개의 숫자로 주어져 있다. 당신은 지금까지 주식이라는 것을 거래해본 적이 없기 대문에, 증권회사에 가서 거래를 시작하기로 했다. 미래를 알면서 주식을 거래한다면 다른 사람들이 의심할지도 모른다는 생각이 들어서, 총 K 번 주식을 사기로 했다. 하루에는 주식을 한 번만 살수 있기 때문에, 주식을 사는 날은 총 K 일이다.
의심을 더 줄이기 위해서, 주식을 살 때마다 맨 처음을 제외하고는 바로 직전에 주식을 샀을 때보다 가격이 올라갔을 때만 사기로 했다.
```python
import sys
T = int(input())
dic = []
for _ in range(T) :
N, K = map(int, input().split())
date = list(map(int, input().split()))
count = 1
for i in range(2,N) :
if date[i-1] < date[i] :
count += 1
else :
continue …
```
=> [DSCT-25] GitHub PR 5주차

sohds/w6/문제풀이/[PGS] 2016년.py, sohds/w6/문제풀이/[PGS] 과일 장수.py, sohds/w6/문제풀이/[PGS] 숫자 문자열과 영단어.py, sohds/w6/발제문제/[BOJ] 123더하기.py, sohds/w6/발제문제/[BOJ] 떡 먹는 호랑이.py
<h1>6주차 목표
: 다이나믹 프로그래밍 알고리즘 문제 해결</h1>
---
정수 4를 1, 2, 3의 합으로 나타내는 방법은 총 7가지가 있다. 합을 나타낼 때는 수를 1개 이상 사용해야 한다.
- 1+1+1+1
- 1+1+2
- 1+2+1
- 2+1+1
- 2+2
- 1+3
- 3+1
정수 n이 주어졌을 때, n을 1, 2, 3의 합으로 나타내는 방법의 수를 구하는 프로그램을 작성하시오.
1. 테스트 케이스 입력받고,
2. 제한으로 걸려있던 `n은 양수이며 11보다 작다.` 라는 조건에 맞게 dp 배열을 초기화해준다.
3. 점화식을 세워 테스트 개수만큼을 반복하면서 dp 배열을 출력한다.
```python
import sys
t = int(input())
n_limit = 11
dp = [0] * (n_limit)
dp[1], dp[2], dp[3] = 1, 2, 4
for i in range(4, n_limit):
dp[i] = dp[i-1] + dp[i-2] + dp[i-3]
for _ in range(t):
test_no = int(input())
print(dp[test_no])
```
나는 바보다. 정말 바보다.. ㅋㅋㅋㅋ 점화식을 엥.. 어떻.. 어떻게 세워야 하지? 라고 생각하다가 결국 답지를 봤다 ^^.. 플로우 자체는 금방 캐치했는데, 점화식을 세우기 위한 머리 쓰기가 싫었나.. 보다.. ㅎㅎ 오히려 뒷문제가 더 어려웠는데 그냥 점화식이 풀기 귀찮아서 안 푼 것 같아 조금 더 인내를 …
=> [DSCT-32] W6 다이나믹 프로그래밍 알고리즘 문제 해결

NaK/NaK_week6/BOJ_2502.py, NaK/NaK_week6/BOJ_9095.py, NaK/NaK_week6/PGS_약수구하기.py, NaK/NaK_week6/PGS_영어가싫어요.py, NaK/NaK_week6/PGS_인덱스바꾸기.py, NaK/NaK_week6/PGS_한번만등장한문자.py
테스트 케이스의 개수(T) 입력
정수 n이 T만큼 입력
1 -> 1 (1)
2 -> 2 (1+1, 2)
3 -> 4 (1+1+1, 1+2, 2+1, 3)
4 -> 7 (1+1+1+1, 1+1+2, 1+2+1, 2+1+1, 1+3, 3+1, 2+2)
5 -> 13
6 -> 24
...
T가 4이상일 때 직전 T 3개의 방법의 수 덧셈
1. T만큼 반복
2. 반복문 안에서 n 입력받기 (for i in range(1,n+1))
2-1. 입력 받은 수가 1일 때 == 1, 2일 때 == 2, 3일 때 == 4
2-2. 입력 받은 수가 4 이상일 때 [i-1] + [i-2] + [i-3]
2-3. i가 입력 받은 수가 될 때까지 반복
```
import sys
T = int(sys.stdin.readline())
answer = []
for i in range(T):
n = int(sys.stdin.readline())
dp = [0] * (n+1)
for j in range(1,n+1):
if j == 1:
dp[j] = 1
elif j == 2:
dp[j] = 2
elif j == 3:
dp[j] = 4
else:
dp[j] = dp[j-1] + dp[j-2] + dp[j-3]
answer.append(dp[n])
for k in range(T):
print(answer[k])
```
```
import sys
T = int(sys.stdin.readline())
answer = []
for i in range(T):
n = int(sys.stdin.readline())
sum_number = []
for j …
```
=> [DSCT-33] GitHub PR 6주차

Moon-ye-rin/[2]1주차/[백준]#1449 수리공 항승.py, Moon-ye-rin/[2]1주차/[백준]#1541 잃어버린 괄호.py, Moon-ye-rin/[2]1주차/[프로그래머스] A로 B 만들기.py, Moon-ye-rin/[2]1주차/[프로그래머스] k의 개수.py, Moon-ye-rin/[2]1주차/[프로그래머스] 이진수 더하기.py, Moon-ye-rin/[2]1주차/[프로그래머스] 치킨 쿠폰.py
**📍작성한 플로우**
- 식의 값을 최소로 만드려면?
- 마이너스 기호를 기준으로 괄호를 쳐야 함
- + 기호인것 끼리 먼저 더한 후, 마지막에 빼기 연산 수행
- 문자열을 마이너스 기호를 기준으로 분리 후 리스트로 저장
- 저장된 문자열은 단일 숫자 혹은 숫자와 +기호로 되어있을것
- 저장된 문자열에서 +기호가 있을 경우 +기호를 기준으로 분리 후 더하기 연산 수행
- 수행 후 최종 저장된 리스트에 있는 숫자들을 모두 빼기 연산으로 수행
**📍작성한 코드**
```python
import sys
input = sys.stdin.read
data = input().strip().splitlines()
arr = data[0].split('-')  # 마이너스기호를 기준으로 분리
for i in range(len(arr)):
if '+' in arr[i]:
arr[i] = sum(map(int, arr[i].split('+')))  # + 연산을 수행한 값 저장
else:
arr[i] = int(arr[i])  # 단일 숫자도 int로 변환
answer = arr[0]
for j in range(1, len(arr)):
answer -= arr[j]
print(answer)
```
**📍소감**
- 연산 값이 최소가 되는 경우를 생각하는 부분에서 조금 시간이 걸리긴 했지만 수학적 접근만 제대로 하면 그 뒤는 무난하게 풀 수 있는 문제라 비교적 간단하게 풀었던 것 같습니다.
---
**📍작성한 플로우**
- N: 물이 새는 곳의 개수, L: 테이프의 길이
- 두번째 줄은 물이 새는 곳의 위치 (N개 만큼)
- …
=> [DSCT-35] GitHub PR 1주차

sua/w1_2/baekjoon_w1_2_1.py, sua/w1_2/baekjoon_w1_2_2.py, sua/w1_2/programmers_w1_2_1.py, sua/w1_2/programmers_w1_2_2.py, sua/w1_2/programmers_w1_2_3.py, sua/w1_2/programmers_w1_2_4.py
🔵 플로우
1. 식 입력 받기
2. '- '기호를 기준으로 분리
3. 1번째 리스트의 항목들을 모두 더함
4. 그 이후의 리스트의 경우 각 리스트의 항목들을 더한 후 f에서 뺌
5. 최종 결과인 f 출력
🔵 코드
```python
n=input()
s=n.split('-')
f = sum(map(int, s[0].split('+')))
for i in range(1, len(s)):
f -= sum(map(int, s[i].split('+')))
print(f)
```
🔵 피드백
최소가 될 수 있는 방법을 찾는 데에 시간이 오래 걸렸습니다.
이런 사고를 빠르게 할 수 있도록 더 노력해야 함을 느꼈습니다.
---
🔵 플로우
1. n(물이 새는 곳의 개수), l(테이프의 길이) 입력 받기
2. water(물이 새는 곳의 위치) 입력 받기
3. 물 새는 곳의 위치 오름차순으로 정렬
4. i(물의 위치를 알기 위한 인덱스), tape(필요한 테이프) 세팅
5. 물이 있는 모든 위치를 돌며 테이프 카운트
6. 새로운 테이프가 필요하면 tape 값 증가
7. i번의 위치에서 시작
8. 시작 위치에서 l만큼을 더하고 1만큼을 뺀 위치에서 끝
9. 물의 위치가 테이프의 범위 안에 있는지 확인
10. 테이프 개수 출력
🔵 코드
```python
n, l = map(int, input().split()) 
water = list(map(int, input().split()))
water.sort(reverse=False)
i = 0
tape = 0
while i <len(water):
tape += 1
start = …
```
=> [DSCT-37] GitHub PR 1주차

NaK/NaK_week7/BOJ_1449.py, NaK/NaK_week7/BOJ_1541.py, NaK/NaK_week7/PGS_가장큰수찾기.py, NaK/NaK_week7/PGS_문자열계산하기.py, NaK/NaK_week7/PGS_배열의 유사도.py, NaK/NaK_week7/PGS_편지.py
'+','-'를 기준으로 제일 끝 숫자에 괄호를 쳐 모든 경우의 수 도출
가장 작은 수 출력
가장 작은 수는 '-'를 마지막에 계산
'-' 기준으로 괄호 치기
```
import sys
num = sys.stdin.readline().strip().split('-') # '-' 기준으로 분할
cal = [] # 괄호 안의 수식 계산 후 리스트로 저장
for i in num:
cal.append(eval(i)) # 괄호 안 수식 계산
answer = cal[0]
for j in range(1,len(cal)):
answer -= cal[j]
print(answer)
```
```
num = input().strip().split('-')
cal = [sum(map(int, part.split('+'))) for part in num]
answer = cal[0]
for j in range(1, len(cal)):
answer -= cal[j]
print(answer)
```
백준 제출 과정에 런타임 에러가 발생하여 GPT에게 물어보고 해결하였다.
- sys.stdin.readline() 보다 input()이 빈 문자열을 받을 때 더 안정적으로 받음
- eval()을 사용하게 되면 보안과 안정성 문제로 피하는 것이 좋음
이러한 답변을 받아 수정하게 되었다. eval()은 간편하여 자주 사용했었는데 이러한 문제가 있는 것을 이제 알게 되어 사용하는 것을 자제하게 될 것 같다.
```
n,l = map(int, input().split())
data = list(map(int, input().split())) …
```
=> [DSCT-38] GitHub PR 1주차

N4YE/2차 스터디/W2/baekjoon_1138번_한줄로서기.py, N4YE/2차 스터디/W2/baekjoon_23351번_물주기.py
제가 실수로 merge 없이 pr을 진행해서 엔터만 넣고 새로 pr 합니다 ^ㅡㅠ
---
2주차 PR (@N4YE) 
---
랑이 집사는 고양이들이 좋아한다는 캣닢을 직접 재배하려고 한다. 일직선으로 놓여진 N개의 화분에 캣닢이 하나씩 심어져 있고, 각 화분은 초기에 K만큼의 수분을 머금고 있다. 랑이 집사가 연속된 A개의 화분에 물을 주면, 물을 준 화분의 수분은 B만큼씩 증가한고 하루가 지나면 모든 화분의 수분이 1씩 감소한다. 수분이 0이 된 화분에 있는 캣닢은 죽는다면, 모든 캣닢이 살아 있는 기간이 최대한 길어지도록 물을 줄 때 첫 캣닢이 죽는 날짜를 출력하는 프로그램을 작성하시오. 단, 첫 날은 1일이다.
- 입력
첫째 줄에 자연수 N, K, A, B가 공백을 사이에 두고 주어진다.
- 출력
모든 캣닢이 살아 있는 기간이 최대한 길어지도록 물을 줄 때, 첫 캣닢이 죽는 날짜를 출력한다.
```python
import sys
N, K, A, B = map(int, input().split())
plant = [K for _ in range(N)]
day = 0
while True :
plant.sort()                    # 리스트 오름차순 정렬
for i in range(A) :
plant[i] = plant[i] + B     # 작은 값부터 A개에 B씩 물 주기
for x in range(N) :
plant[x] = plant[x] - 1 …
```
=> [DSCT-41] 2차 Week2 (@N4YE)

NaK/NaK_week8/BOJ_1138.py, NaK/NaK_week8/BOJ_23351.py, NaK/NaK_week8/PGS_OX퀴즈.py, NaK/NaK_week8/PGS_n의배수고르기.py, NaK/NaK_week8/PGS_숫자찾기.py, NaK/NaK_week8/PGS_자릿수더하기.py, NaK/NaK_week9/BOJ_16173.py, NaK/NaK_week9/BOJ_4963.py, NaK/NaK_week9/PGS_문자열안에문자열.py, NaK/NaK_week9/PGS_문자열정렬하기2.py, NaK/NaK_week9/PGS_세균증식.py, NaK/NaK_week9/PGS_제곱수판별하기.py
N = 4
h = [2, 1, 1, 0]
키가 1인 사람의 왼쪽이 2명
키가 2인 사람의 왼쪽이 1명
키가 3인 사람의 왼쪽이 1명
키가 4인 사람의 왼쪽이 0명
반목문 N(4)번
키가 1인 사람(i+1): 왼쪽이 2명 1의 자리는 앞에 2칸 비우기(3번째 자리)
키가 2인 사람: 왼쪽이 1명 키가 1 앞자리에 2칸 자리(1+1)가 있으면 앞에 1칸 비우기 (2번째 자리) -> 키가 1 앞자리에 자리가 없으면 채워진 칸의 뒷자리
키가 3인 사람: 왼쪽이 1명 키가 2 앞자리에 2칸 자리(1+1)가 있으면 앞에 1칸 비우고, 없으면 채워진 칸의 뒷자리
키가 4인 사람: 마지막 비워진 칸
```
N = int(input())
h = list(map(int,input().split()))
answer = [0]*N
for i in range(N):
cnt = 0
for j in range(N):
if cnt == h[i] and answer[j] == 0:
answer[j] = i+1
break
elif answer[j] == 0:
cnt += 1
print(' '.join(map(str,answer)))
```
플로우 작성할 때 코드를 작성하는 방법보다는 문제의 이해를 위해 풀어서 작성한 거라 좀 복잡하게 작성 되었다. 그치만 이렇게 문제가 이해하기 힘들 때 풀어서 작성하니 이전보다 이해하는 시간이 줄어서 괜찮은 것 같았다.
화분에 수분이 0일 때까지 반복
A개의 화분에 B씩 물주기
모든 화분의 수분이 1씩 감소
수분이 적은 화분에 물주기(정렬)
```
L = list(map(int, …
```
=> [DSCT-43] GitHub PR 2주차

sua/w2_2/baekjoon_w2_2_1.py, sua/w2_2/baekjoon_w2_2_2.py, sua/w2_2/programmers_w2_2_1.py, sua/w2_2/programmers_w2_2_2.py, sua/w2_2/programmers_w2_2_3.py, sua/w2_2/programmers_w2_2_4.py
🔵 플로우
1. 사람 수 입력 받기
2. 본인 앞에 있어야 하는 사람의 수를 나타내는 리스트 입력 받기
3. 결과 리스트 초기화
4. 사람 배치
5. 빈 자리 개수 세는 변수 세팅
6. 왼쪽부터 빈 자리 찾으면서 위치 찾기
7. 원하는 빈 자리 개수와 같아지면 배치
8. 결과 출력
🔵 코드
```python
n = int(input())
length = list(map(int, input().split()))
result = [0] * n
count = 0
for j in range(n):
if result[j] == 0:
if count == length[i]:
result[j] = i+1
break
count +=1
print(" ".join(map(str, result)))
```
🔵 피드백
처음에 문제 이해를 잘못 하여 계속 틀린 답을 제출하게 되었습니다.
그래서 어느 부분을 잘못 이해한 것인지 다른 분들의 문제 해석을 보게 되었고 이해를 마친 후에 다시 코드를 작성하였습니다.
그런데도 자꾸 문제가 틀리길래 어느 부분이 틀린 것인지 모르겠어서 다른 분들의 답과 비교해보고 지피티에게 틀린 부분을 알려달라고 하였고 print 부분을 잘못 작성한 것을 알려주었습니다.
문제를 좀 더 자세히 보고 꼼꼼히 코드를 체크하는 습관을 길러야겠습니다.
---
🔵 플로우
1. n(화분 개수), k(초기 수분량), a(물 줄 화분 개수), b(물 준 화분의 수분량) 입력 받기
2. 모든 화분의 수분 상태가 k인 arr 리스트 생성
3. day를 0으로 세팅
4. arr 리스트에 0이 …
=> [DSCT-39] GitHub PR 2주차

sua/w4_2/baekjoon_w4_2_1.py, sua/w4_2/baekjoon_w4_2_2.py, sua/w4_2/programmers_w4_2_1.py, sua/w4_2/programmers_w4_2_2.py, sua/w4_2/programmers_w4_2_3.py, sua/w4_2/programmers_w4_2_4.py
🔵 플로우
1. n,m 입력 받기
2. 2차월 리스트 city 생성
3. 방문 여부 저장 리스트 새성
4. 이동방향 정의
5. bfs 함수 정의
6. 시작점을 큐에 넣고 방문 처리
7. 큐에서 현재 위치를 꺼냄
8. 도착지점에 방문하면 "Yes"를 출력하고 리턴
9. 오른쪽 또는 아래쪽으로 한칸 이동
10. 다음 칸이 격자 안에 있고 이동 가능하고 방문하지 않은 곳이면 큐에 추가
11. 도착지점에 도달하지 못했다면 "No" 출력
🔵 코드
```python
from collections import deque
n, m = map(int, input().split()) 
city = []
for _ in range(m): 
city.append(list(map(int, input().split())))
visited = [[False]*n for _ in range(m)]
directions = [(0, 1), (1, 0)]  # (dy, dx)
def bfs(city, start, visited):
m= len(city)
n= len(city[0])
queue = deque([start])
visited[0][0] = True
while queue:
y,x = queue.popleft()
if (y, x) == (m-1, n-1):
print("Yes")
return
for dy, dx in directions:
ny = y +dy
nx = x+dx
if 0 <= ny < m and 0 <=nx < n:
if city[ny][nx] == 1 and not visited[ny][nx]: …
```
=> [DSCT-50] GitHub PR 4주차

N4YE/2차 스터디/W5/baekjoon_10825번_국영수.py, N4YE/2차 스터디/W5/baekjoon_2217번_로프.py
5주차 PR (@N4YE) 
---
도현이네 반 학생 N명의 이름과 국어, 영어, 수학 점수가 주어진다. 이때, 다음과 같은 조건으로 학생의 성적을 정렬하는 프로그램을 작성하시오.
1. 국어 점수가 감소하는 순서로
2. 국어 점수가 같으면 영어 점수가 증가하는 순서로
3. 국어 점수와 영어 점수가 같으면 수학 점수가 감소하는 순서로
4. 모든 점수가 같으면 이름이 사전 순으로 증가하는 순서로 (단, 아스키 코드에서 대문자는 소문자보다 작으므로 사전순으로 앞에 온다.)
- 입력
첫째 줄에 도현이네 반의 학생의 수 N (1 ≤ N ≤ 100,000)이 주어진다. 둘째 줄부터 한 줄에 하나씩 각 학생의 이름, 국어, 영어, 수학 점수가 공백으로 구분해 주어진다. 점수는 1보다 크거나 같고, 100보다 작거나 같은 자연수이다. 이름은 알파벳 대소문자로 이루어진 문자열이고, 길이는 10자리를 넘지 않는다.
- 출
문제에 나와있는 정렬 기준으로 정렬한 후 첫째 줄부터 N개의 줄에 걸쳐 각 학생의 이름을 출력한다.
```python
import sys
N = int(input().strip())
students = [input().split() for _ in range(N)]
students = [[name, int(kor), int(eng), int(math)] for name, kor, eng, math in students]
students.sort(key=lambda x: …
```
=> [DSCT-53] Week5 (@N4YE)

sua/w5_2/baekjoon_w5_1.py, sua/w5_2/baekjoon_w5_1_2.py, sua/w5_2/baekjoon_w5_2.py, sua/w5_2/programmers_w5_2_1.py, sua/w5_2/programmers_w5_2_2.py, sua/w5_2/programmers_w5_2_3.py, sua/w5_2/programmers_w5_2_4.py
🔵 플로우
1. n 입력 받기
2. 입력 받은 정보를 각각 이름, 국어, 영어, 수학으로 저장하고 리스트에 추가
3. 국어는 내림차순, 영어는 오름차순, 수학은 내림차순, 이름은 오름차순으로 정렬
4. 결과 출력
🔵 코드
1. 처음에 작성한 코드
```python
n = int(input()) 
students = []
for _ in range(n):
student = input().split()
name = student[0]
korean = int(student[1])
english = int(student[2])
math = int(student[3])
students.append((name, korean, english, math))
for j in range(i + 1, n):
if students[i][1] < students[j][1]:
students[i], students[j] = students[j], students[i]
elif students[i][1] == students[j][1] and students[i][2] > students[j][2]:
students[i], students[j] = students[j], students[i]
elif students[i][1] == students[j][1] and students[i][2] == students[j][2] and students[i][3] < students[j][3]:
students[i], students[j] = students[j], students[i]
elif …
```
=> [DSCT-54] GitHub PR 5주차

sohds/spring/w6/문제풀이/[boj] 국영수.py, sohds/spring/w6/문제풀이/[boj] 로프.py, sohds/spring/w6/문제풀이/[boj] 폴짝폴짝.py, sohds/spring/w6/발제문제/[boj] 단어 정렬.py, sohds/spring/w6/발제문제/[boj] 버블 소트.py
<h1>6주차 목표
: 정렬 알고리즘 문제 해결</h1>
- 금주 문제 풀이부터 프로그래머스 코드와 비슷하게 가기 위해 함수 정의 후 푸는 형식으로 진행하겠습니다!
---
알파벳 소문자로 이루어진 N개의 단어가 들어오면 아래와 같은 조건에 따라 정렬하는 프로그램을 작성하시오.
1. 길이가 짧은 것부터
2. 길이가 같으면 사전 순으로
단, 중복된 단어는 하나만 남기고 제거해야 한다.
- 입력받은 단어 리스트를 처리하는 함수
1. set()을 사용하여 중복된 단어를 제거
2. list()로 다시 변환하여 리스트로 만듦
3. sort()로 알파벳 순서대로 정렬
4. sort(key=len)으로 단어의 길이를 기준으로 정렬
5. 정렬된 단어 리스트를 반환
```python
import sys
n = int(input())
def word_sort(n, words):
words = list(set(words))
words.sort()
words.sort(key=len)
return words
words = [input().strip() for _ in range(n)]
words = word_sort(n, words)
print(*words, sep='\n')
```
너무 오랜만에 코테 문제를 풀어서 그런지 뇌가 굳은 것 같다. 이 쉬운 문제조차 어떻게 풀지 잠깐 생각하는 시간을 가졌다. 문제를 풀다가 '단, 중복된 단어는 하나만 남기고 제거해야 한다.' 라는 조건을 빼먹고 봐서 계속해서 틀려서 뭐가 틀렸나 다시 …
=> [DSCT-56] W6 정렬 알고리즘 문제 해결

N4YE/2차 스터디/W6/baekjoon_1181번_단어정렬.py, N4YE/2차 스터디/W6/baekjoon_1517번_버블소트.py
6주차 PR (@N4YE) 
---
알파벳 소문자로 이루어진 N개의 단어가 들어오면 아래 같은 조건에 따라 정렬하는 프로그램을 작성하시오.
1. 길이가 짧은 것부터
2. 길이가 같으면 사전 순으로
단, 중복된 단어는 하나만 남기고 제거해야 한다.
- 입력
첫째 줄에 단어의 개수 N이 주어진다. (1 ≤ N ≤ 20,000) 둘째 줄부터 N개의 줄에 걸쳐 알파벳 소문자로 이루어진 단어가 한 줄에 하나씩 주어진다. 주어지는 문자열의 길이는 50을 넘지 않는다.
- 출력
조건에 따라 정렬하여 단어들을 출력한다.
```python
import sys
N = int(input().strip())                    #단어 개수
word = [input().strip() for _ in range(N)]  #단어 리스트
word = sorted(list(set(word)))              #리스트 중복 제거
word.sort(key=len)                          #리스트 길이순 정렬
for x in word :
print(x)
```
print에서 계속 enter가 포함되어 출력되어서 계속 오류가 생겼는데, word 리스트에 input을 사용할 때 \n이 포함되어 저장되므로 strip()을 통해 줄바꿈을 제거해줘야 한다는 것을 알게되었습니다. 흐름이 쉬워서 쉽게 해결했는데 GPT를 통해 최적화를 부탁했더니 받은 코드에서는 sort 명령어에 …
=> [DSCT-55] Week6 (@N4YE)

NaK/NaK_week12/BOJ_1181.py, NaK/NaK_week12/BOJ_1517.py, NaK/NaK_week12/PGS_7의개수.py, NaK/NaK_week12/PGS_머쓱이보다키큰사람.py, NaK/NaK_week12/PGS_잘라서배열로저장하기.py, NaK/NaK_week12/PGS_중복된숫자개수.py
- 첫째 줄에 단어의 개수 N
- 길이가 짧은 것부터, 길이가 같으면 사전 순으로
- 중복은 제거
- 길이는 len 사용?
- 정렬 뭐 쓰지.. 삽입? 퀵?
- word 길이로 정렬해야 하는데 퀵으로 어떻게 쓸지 잘 모르겠음...
```
N = int(input())
word = []
for _ in range(N):
w = input()
if w not in word:
word.append(w)
for i in range(1,len(word)):
for j in range(i,0,-1):
if (len(word[j]) < len(word[j-1]) # 길이로
or (len(word[j]) == len(word[j-1]) and word[j] < word[j-1])): # 사전 순으로
word[j], word[j - 1] = word[j - 1], word[j]
else:
break
for k in word:
print(k)
```
```
N = int(input())
words = {input() for _ in range(N)}  # set으로 중복 제거
sorted_words = sorted(words, key=lambda x: (len(x), x))
print('\n'.join(sorted_words))
```
위 코드는 시간 초과가 발생했는데 수정해도 시간 초과가 발생했다. 정렬 코드를 직접 작성하고 싶었는데 이것 때문에 시간 초과가 발생한 것 같다.
그래서 아래 코드는 지피티가 수정해준 코드인데 역시나 파이썬 내장함수를 쓰는게 현명하고 빠른 길이었다.
추가로 다른 사람들 코드도 찾아봤다. 나는 …
=> [DSCT-57] GitHub PR 6주차

N4YE/2차 스터디/W7/baekjoon_15810번_풍선공장.py, N4YE/2차 스터디/W7/baekjoon_7795번_먹을것인가먹힐것인가.py
7주차 PR (@N4YE) 
---
심해에는 두 종류의 생명체 A와 B가 존재한다. A는 B를 먹는다. A는 자기보다 크기가 작은 먹이만 먹을 수 있다. 예를 들어, A의 크기가 {8, 1, 7, 3, 1}이고, B의 크기가 {3, 6, 1}인 경우에 A가 B를 먹을 수 있는 쌍의 개수는 7가지가 있다. 8-3, 8-6, 8-1, 7-3, 7-6, 7-1, 3-1.  두 생명체 A와 B의 크기가 주어졌을 때, A의 크기가 B보다 큰 쌍이 몇 개나 있는지 구하는 프로그램을 작성하시오.
- 입력
첫째 줄에 테스트 케이스의 개수 T가 주어진다. 각 테스트 케이스의 첫째 줄에는 A의 수 N과 B의 수 M이 주어진다. 둘째 줄에는 A의 크기가 모두 주어지며, 셋째 줄에는 B의 크기가 모두 주어진다. 크기는 양의 정수이다. (1 ≤ N, M ≤ 20,000)
- 출력
각 테스트 케이스마다, A가 B보다 큰 쌍의 개수를 출력한다.
```python
import sys
T = int(input())
for _ in range(T):
n, m = map(int,input().split())
a = list(map(int, input().split()))
b = list(map(int, input().split()))
a.sort()
b.sort()
answer = 0
for j in range(m):
if a[i] > b[j]:
answer += 1
else:
break …
```
=> [DSCT-63] Week7 (@N4YE)

NaK/NaK_week13/BOJ_15810.py, NaK/NaK_week13/BOJ_7795.py
- 테스트 케이스 입력: T
- A의 수: N, B의 수: M 입력
- A의 크기 입력 -> 리스트: Asize
- B의 크기 입력 -> 리스트: Bsize
- for문으로 Asize 개수만큼 돌리고 Bsize의 각 값들과 하나씩 비교
-> 이진탐색, 중간점 탐색소거 방식으로 변경
- A가 B보다 큰 쌍의 개수 출력
```
T = int(input())
answer = []
for _ in range(T):
N,M = map(int,input().split())
Asize = list(map(int, input().split()))
Bsize = list(map(int, input().split()))
count = 0
for i in Asize:
for j in Bsize:
if i > j:
count += 1
answer.append(count)
for k in answer:
print(k)
```
```
import bisect
T = int(input())
answer = []
for _ in range(T):
N, M = map(int, input().split())
Asize = list(map(int, input().split()))
Bsize = list(map(int, input().split()))
Bsize.sort()
count = 0
for a in Asize:
count += bisect.bisect_left(Bsize, a)
answer.append(count)
for k in answer:
print(k)
```
```
def lower_bound(arr, target): …
```
=> [DSCT-61] GitHub PR 7주차

sohds/spring/w7/[boj] 먹을 것인가 먹힐 것인가.py, sohds/spring/w7/[boj] 풍선 공장.py
<h1>7주차 목표
: 정렬 알고리즘 문제 해결</h1>
---
심해에는 두 종류의 생명체 A와 B가 존재한다. A는 B를 먹는다. A는 자기보다 크기가 작은 먹이만 먹을 수 있다. 예를 들어, A의 크기가 {8, 1, 7, 3, 1}이고, B의 크기가 {3, 6, 1}인 경우에 A가 B를 먹을 수 있는 쌍의 개수는 7가지가 있다. 8-3, 8-6, 8-1, 7-3, 7-6, 7-1, 3-1.
두 생명체 A와 B의 크기가 주어졌을 때, A의 크기가 B보다 큰 쌍이 몇 개나 있는지 구하는 프로그램을 작성하시오.
- A와 B 배열을 모두 정렬
- A의 각 원소에 대해서
- B 배열을 처음부터 순회하면서 A[i] > B[j]인 경우를 찾음
- B 배열의 끝에 도달하거나 A[i] ≤ B[j]가 되는 순간에
- 현재까지의 cnt 값을 pair에 더함
- A[i]보다 작은 B의 원소들의 개수 의미
- 최종적으로 pair 값이 A[i] > B[j]인 모든 쌍의 개수 출력
```python
import sys
def ab_pair(n, m, a, b):
cnt = 0
pair = 0
a.sort()
b.sort()
while 1:
if cnt == m or a[i] <= b[cnt]:
pair += cnt
break
else:
cnt += 1
return pair
t = int(input())
for _ in range(t):
n, m = map(int, input().split()) …
```
=> [DSCT-62] W7 정렬 알고리즘 문제 해결

N4YE/2차 스터디/W8/baekjoon_16401번_과자나눠주기.py, N4YE/2차 스터디/W8/baekjoon_2343번_기타레슨.py
8주차 PR (@N4YE) 
---
명절이 되면, 홍익이 집에는 조카들이 놀러 온다. 떼를 쓰는 조카들을 달래기 위해 홍익이는 막대 과자를 하나씩 나눠준다. 조카들이 과자를 먹는 동안은 떼를 쓰지 않기 때문에, 홍익이는 조카들에게 최대한 긴 과자를 나눠주려고 한다. 그런데 나눠준 과자의 길이가 하나라도 다르면 조카끼리 싸움이 일어난다. 따라서 반드시 모든 조카에게 같은 길이의 막대 과자를 나눠주어야 한다.
M명의 조카가 있고 N개의 과자가 있을 때, 조카 1명에게 줄 수 있는 막대 과자의 최대 길이를 구하라. 단, 막대 과자는 길이와 상관없이 여러 조각으로 나눠질 수 있지만, 과자를 하나로 합칠 수는 없다. 단, 막대 과자의 길이는 양의 정수여야 한다.
- 입력
첫째 줄에 조카의 수 M (1 ≤ M ≤ 1,000,000), 과자의 수 N (1 ≤ N ≤ 1,000,000)이 주어진다. 둘째 줄에 과자 N개의 길이 L1, L2, ..., LN이 공백으로 구분되어 주어진다. 과자의 길이는 (1 ≤ L1, L2, ..., LN ≤ 1,000,000,000) 를 만족한다.
- 출력
첫째 줄에 조카 1명에게 줄 수 있는 막대 과자의 최대 길이를 출력한다.
단, 모든 조카에게같은 길이의 막대과자를 나눠줄 수 없다면, 0을 출력한다.
```python
import sys
m, n = map(int, input().split())     # 사람 m명, 쿠기 n개
cookies = list(map(int, …
```
=> [DSCT-65] Week8 (@N4YE)

sua/w8/baekjoon_w8_1.py, sua/w8/baekjoon_w8_2.py, sua/w8/programmers_w8_1.py, sua/w8/programmers_w8_2.py, sua/w8/programmers_w8_3.py, sua/w8/programmers_w8_4.py
🔵 플로우
1. M(조카 수), N(과자 수) 입력 받기
2. 과자 길이 입력 받기
3. 과자의 최소 길이는 1, 최대 길이는 과자 중 길이가 가장 긴 것으로 지정
4. 최소 길이가 최대 길이보다 작거나 같은 범위 안에서 반복
5. 중앙값은 (min_length + max_length) // 2로 계산
6. children(조카들에게 나눠줄 수 있는 과자의 개수) 세팅
7. 각 과자들을 중앙값으로 나눈 몫을 구하여 총합을 구함
8. 만약 children(조카에게 나눠줄 수 있는 과자의 개수)이 M(조카 수)보다 크거나 같다면 min_length를 mid+1로 조정
9. 그렇지 않고 M(조카 수)보다 적게 나오면 max_length를 mid-1로 조정
10. 가능한 최대 길이인 max_length 출력
🔵 코드
```python
import sys
M, N = map(int, input().strip().split())
snacks = list(map(int, input().split()))
min_length, max_length = 1, max(snacks)
while min_length <= max_length:
mid = (min_length + max_length)//2
children = 0
for i in range(N):
children = children + (snacks[i] // mid)
if children >= M:
min_length = mid +1
else:
max_length = mid -1
print(max_length)
```
🔵 …
=> [DSCT-70] GitHub PR 8주차
